import type { Difficulty } from '@gitype/shared';

const MIN_CHARS = 200;
const MAX_CHARS = 800;

const BRACE_BLOCK_LANGUAGES = new Set([
  'typescript',
  'javascript',
  'java',
  'c',
  'cpp',
  'csharp',
  'go',
  'rust',
  'php',
  'kotlin',
  'swift',
]);

// Top-level (non-indented) declaration starts for brace languages. Heuristic:
// counts braces character-by-character, so a brace inside a string/comment
// can throw off block detection — acceptable for a v1 extractor since a
// misdetected block just gets rejected by the size bounds, not corrupted.
const BRACE_DECLARATION_PATTERN =
  /^(export\s+)?(default\s+)?(public\s+|private\s+|protected\s+|static\s+|async\s+|pub\s+)*(function\b|class\b|interface\b|struct\b|impl\b|enum\b|func\b|fn\b)/;

const GENERATED_MARKERS = [
  /@generated/i,
  /do not edit/i,
  /code generated by/i,
  /this file is automatically generated/i,
];

const SECRET_PATTERNS = [
  /AKIA[0-9A-Z]{16}/, // AWS access key id
  /-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----/,
  /(secret|token|api[_-]?key|password)\s*[:=]\s*['"][A-Za-z0-9+/=_-]{16,}['"]/i,
];

function looksGenerated(content: string): boolean {
  const header = content.slice(0, 500);
  return GENERATED_MARKERS.some((pattern) => pattern.test(header));
}

function containsSecret(content: string): boolean {
  return SECRET_PATTERNS.some((pattern) => pattern.test(content));
}

function extractBraceBlocks(content: string): string[] {
  const lines = content.split('\n');
  const blocks: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    if (/^[ \t]/.test(lines[i]) || !BRACE_DECLARATION_PATTERN.test(lines[i]))
      continue;

    let depth = 0;
    let opened = false;
    let endIdx = -1;
    for (let j = i; j < lines.length; j++) {
      for (const ch of lines[j]) {
        if (ch === '{') {
          depth++;
          opened = true;
        } else if (ch === '}') {
          depth--;
        }
      }
      if (opened && depth === 0) {
        endIdx = j;
        break;
      }
    }

    if (endIdx === -1) continue; // unbalanced within the file — skip
    blocks.push(lines.slice(i, endIdx + 1).join('\n'));
    i = endIdx;
  }

  return blocks;
}

function extractPythonBlocks(content: string): string[] {
  const lines = content.split('\n');
  const blocks: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    if (!/^(def|class)\s/.test(lines[i])) continue;

    let endIdx = lines.length - 1;
    for (let j = i + 1; j < lines.length; j++) {
      if (lines[j].trim() === '') continue;
      if (!/^[ \t]/.test(lines[j])) {
        endIdx = j - 1;
        break;
      }
    }

    blocks.push(
      lines
        .slice(i, endIdx + 1)
        .join('\n')
        .trimEnd(),
    );
    i = endIdx;
  }

  return blocks;
}

function extractCandidateBlocks(content: string, language: string): string[] {
  if (language === 'python') return extractPythonBlocks(content);
  if (BRACE_BLOCK_LANGUAGES.has(language)) return extractBraceBlocks(content);
  return [];
}

/** Pure: carves a typing-game-sized snippet out of a file, or returns null if nothing qualifies. */
export function extractSnippet(
  content: string,
  language: string,
): string | null {
  if (looksGenerated(content)) return null;

  const whole = content.trim();
  if (
    whole.length >= MIN_CHARS &&
    whole.length <= MAX_CHARS &&
    !containsSecret(whole)
  ) {
    return whole;
  }

  const candidate = extractCandidateBlocks(content, language)
    .map((block) => block.trim())
    .find(
      (block) =>
        block.length >= MIN_CHARS &&
        block.length <= MAX_CHARS &&
        !containsSecret(block),
    );

  return candidate ?? null;
}

/** Pure: cheap heuristic bucket from size + line length + symbol density. */
export function scoreDifficulty(snippet: string): Difficulty {
  const lines = snippet.split('\n').filter((line) => line.trim().length > 0);
  const avgLineLength =
    lines.reduce((sum, line) => sum + line.length, 0) / lines.length;
  const symbolCount = (snippet.match(/[{}()[\];<>&|^%*+=!~]/g) ?? []).length;
  const symbolDensity = symbolCount / snippet.length;

  const score =
    avgLineLength * 0.5 + symbolDensity * 200 + snippet.length * 0.05;

  // Thresholds are the ~33rd/~66th percentile scores measured across a real
  // ingestion run (208 snippets, express/requests/ripgrep/gin) — the original
  // 25/45 cutoffs were calibrated on guesswork and left HARD absorbing almost
  // everything. Revisit as more languages/repos get ingested.
  if (score < 48) return 'EASY';
  if (score < 58) return 'MEDIUM';
  return 'HARD';
}
